// This file is auto generated by the SwordLord DANG Tiled Exporter.
// It will get overwritten once you re-export your tile map!
// (c) 2019-2021 by SwordLord - the coding crew

// World ------------------------------------------------

static const dang::tmx_world end_scene_world = {
    .width = 18,
    .height = 12,
    .tileWidth = 32,
    .tileHeight = 32
};

// Tilesets ------------------------------------------------

static const dang::tmx_tileset end_scene_tilesets[] = {
    {"gfx_levels_castle_tiles", &gfx_levels_castle_tiles, 96,32,32,384,256,12,8},
    {"gfx_castle_decorations", &gfx_castle_decorations, 32,32,32,256,128,8,4},
    {"gfx_king", &gfx_king, 28,32,32,896,32,28,1},
    {"hammer", &hammer, 15,32,40,480,40,15,1},
    {"king_w_hammer", &king_w_hammer, 2,40,48,80,48,2,1},
};

static const size_t end_scene_tilesets_len = 5;

// Animations ------------------------------------------------

static const dang::tmx_tileanimation end_scene_tileanimations[] = {
    {"gfx_castle_decorations",5,"flicker",{{5, 100},{6, 100},{7, 100},{13, 100},{14, 100},{15, 100}}},
    {"gfx_king",0,"wait",{{0, 100},{1, 100},{2, 100},{3, 100},{4, 100},{5, 100},{6, 100},{0, 800}}},
    {"gfx_king",1,"blink",{{0, 100},{25, 100}}},
    {"gfx_king",7,"jump",{{9, 100},{7, 100}}},
    {"gfx_king",8,"on_air",{{8, 100}}},
    {"gfx_king",10,"walk",{{10, 100},{11, 100},{12, 100},{13, 100},{14, 100},{15, 100},{16, 100},{17, 100}}},
    {"gfx_king",18,"bubble",{{18, 100},{19, 100},{20, 100},{19, 100},{18, 100}}},
    {"gfx_king",21,"life_lost",{{21, 600},{22, 600},{23, 600}}},
    {"hammer",0,"blink",{{0, 100},{1, 100},{2, 100},{3, 100},{4, 100},{5, 100},{6, 100},{7, 100},{8, 100},{9, 100},{10, 100},{11, 100},{12, 100},{13, 100},{14, 100}}},
    {"king_w_hammer",0,"vaevictis",{{0, 400},{1, 400}}},
};

static const size_t end_scene_tileanimations_len = 10;

// Layers ------------------------------------------------

// layer tilelayer: end_scene_bg
static const dang::tmx_tile end_scene_end_scene_bg_tiles[] = {

    {4, 0}, {25, 0}, {25, 0}, {25, 0}, {25, 0}, {25, 0}, {25, 0}, {25, 0}, {25, 0}, {25, 0}, {25, 0}, {25, 0}, {25, 0}, {25, 0}, {25, 0}, {25, 0}, {25, 0}, {5, 0},
    {14, 0}, {48, 0}, {49, 0}, {49, 0}, {49, 0}, {49, 0}, {49, 0}, {49, 0}, {49, 0}, {49, 0}, {49, 0}, {49, 0}, {49, 0}, {49, 0}, {49, 0}, {49, 0}, {50, 0}, {12, 0},
    {14, 0}, {60, 0}, {61, 0}, {61, 0}, {61, 0}, {61, 0}, {61, 0}, {61, 0}, {61, 0}, {61, 0}, {61, 0}, {61, 0}, {61, 0}, {61, 0}, {61, 0}, {61, 0}, {62, 0}, {12, 0},
    {14, 0}, {60, 0}, {61, 0}, {61, 0}, {61, 0}, {61, 0}, {61, 0}, {61, 0}, {61, 0}, {61, 0}, {61, 0}, {61, 0}, {61, 0}, {61, 0}, {61, 0}, {61, 0}, {62, 0}, {12, 0},
    {14, 0}, {60, 0}, {61, 0}, {61, 0}, {61, 0}, {61, 0}, {61, 0}, {61, 0}, {61, 0}, {61, 0}, {61, 0}, {61, 0}, {61, 0}, {61, 0}, {61, 0}, {61, 0}, {62, 0}, {12, 0},
    {14, 0}, {60, 0}, {61, 0}, {61, 0}, {61, 0}, {61, 0}, {61, 0}, {61, 0}, {61, 0}, {61, 0}, {61, 0}, {61, 0}, {61, 0}, {61, 0}, {61, 0}, {61, 0}, {62, 0}, {12, 0},
    {14, 0}, {60, 0}, {61, 0}, {61, 0}, {61, 0}, {61, 0}, {61, 0}, {0, 0}, {1, 0}, {2, 0}, {61, 0}, {61, 0}, {61, 0}, {61, 0}, {61, 0}, {61, 0}, {62, 0}, {12, 0},
    {14, 0}, {60, 0}, {61, 0}, {61, 0}, {61, 0}, {61, 0}, {0, 0}, {17, 0}, {13, 0}, {16, 0}, {2, 0}, {61, 0}, {61, 0}, {61, 0}, {61, 0}, {61, 0}, {62, 0}, {12, 0},
    {14, 0}, {60, 0}, {61, 0}, {61, 0}, {61, 0}, {36, 0}, {41, 0}, {25, 0}, {25, 0}, {25, 0}, {40, 0}, {38, 0}, {61, 0}, {61, 0}, {61, 0}, {61, 0}, {62, 0}, {12, 0},
    {26, 0}, {60, 0}, {61, 0}, {61, 0}, {61, 0}, {61, 0}, {61, 0}, {61, 0}, {61, 0}, {61, 0}, {61, 0}, {61, 0}, {61, 0}, {61, 0}, {61, 0}, {61, 0}, {62, 0}, {12, 0},
    {85, 0}, {89, 0}, {73, 0}, {73, 0}, {73, 0}, {73, 0}, {73, 0}, {73, 0}, {73, 0}, {73, 0}, {73, 0}, {73, 0}, {73, 0}, {73, 0}, {73, 0}, {73, 0}, {74, 0}, {12, 0},
    {1, 0}, {1, 0}, {1, 0}, {1, 0}, {1, 0}, {1, 0}, {1, 0}, {1, 0}, {1, 0}, {1, 0}, {1, 0}, {1, 0}, {1, 0}, {1, 0}, {1, 0}, {1, 0}, {1, 0}, {17, 0}

};

static const size_t end_scene_end_scene_bg_tiles_len = 216;

static const dang::tmx_layer end_scene_end_scene_bg = {
    .name = "end_scene_bg",
    .type = dang::tmx_layerType::ltTile,
    .opacity = 1,
    .visible = true,
    .z_order = 0,
    .position = {0,0},
    .tl_width = 18,
    .tl_height = 12,
    .tl_tileset = "gfx_levels_castle_tiles",
    .tl_tiles = end_scene_end_scene_bg_tiles,
    .tl_tiles_len = end_scene_end_scene_bg_tiles_len,
    .spriteobjects = nullptr,
    .spriteobejcts_len = 0
};

// Objects for layer: end_scene_mood
static const dang::tmx_spriteobject end_scene_end_scene_mood_objects[] = {

    {1,"1","",384,288,32,32,true,"gfx_castle_decorations",4,"",0,0b0000},
    {2,"2","",416,320,32,32,true,"gfx_castle_decorations",4,"",0,0b0000},
    {4,"4","flicker",384,192,32,32,true,"gfx_castle_decorations",5,"",0,0b0000},
    {5,"5","flicker",352,160,32,32,true,"gfx_castle_decorations",5,"",0,0b0000},
    {6,"6","flicker",128,192,32,32,true,"gfx_castle_decorations",5,"",0,0b0000},
    {7,"7","flicker",160,160,32,32,true,"gfx_castle_decorations",5,"",0,0b0000},
    {8,"8","blink",256,152,32,40,true,"hammer",0,"",0,0b0000},
    {9,"9","flicker",288,112,32,32,true,"gfx_castle_decorations",5,"",0,0b0000},
    {10,"10","flicker",224,112,32,32,true,"gfx_castle_decorations",5,"",0,0b0000}

};

static const size_t end_scene_end_scene_mood_objects_len = 9;

static const dang::tmx_layer end_scene_end_scene_mood = {
    .name = "end_scene_mood",
    .type = dang::tmx_layerType::ltObjects,
    .opacity = 1,
    .visible = true,
    .z_order = 1,
    .position = {0,0},
    .tl_width = 0,
    .tl_height = 0,
    .tl_tileset = "",
    .tl_tiles = nullptr,
    .tl_tiles_len = 0,
    .spriteobjects = end_scene_end_scene_mood_objects,
    .spriteobejcts_len = end_scene_end_scene_mood_objects_len
};

// Objects for layer: end_scene_obj
static const dang::tmx_spriteobject end_scene_end_scene_obj_objects[] = {

    {3,"hero","",0,320,32,32,true,"gfx_king",0,"",0,0b0000}

};

static const size_t end_scene_end_scene_obj_objects_len = 1;

static const dang::tmx_layer end_scene_end_scene_obj = {
    .name = "end_scene_obj",
    .type = dang::tmx_layerType::ltObjects,
    .opacity = 1,
    .visible = true,
    .z_order = 2,
    .position = {0,0},
    .tl_width = 0,
    .tl_height = 0,
    .tl_tileset = "",
    .tl_tiles = nullptr,
    .tl_tiles_len = 0,
    .spriteobjects = end_scene_end_scene_obj_objects,
    .spriteobejcts_len = end_scene_end_scene_obj_objects_len
};

const static dang::tmx_layer end_scene_layers[] = {
    end_scene_end_scene_bg,
    end_scene_end_scene_mood,
    end_scene_end_scene_obj,
};

const static size_t end_scene_layers_len = 3;

// Level ---------------------------------------------------

static const dang::tmx_level end_scene_level {
    .w = &end_scene_world,
    .tilesets = end_scene_tilesets,
    .tilesets_len = end_scene_tilesets_len,
    .tileanimations = end_scene_tileanimations,
    .tileanimations_len = end_scene_tileanimations_len,
    .layers = end_scene_layers,
    .layers_len = end_scene_layers_len,
    .waypoints = nullptr,
    .waypoints_len = 0,
    .waypoint_connections = nullptr,
    .waypoint_connections_len = 0,
    .wavepoints = nullptr,
    .wavepoints_len = 0,
    .zones = nullptr,
    .zones_len = 0,
    .zone_passages = nullptr,
    .zone_passages_len = 0
};


