// This file is auto generated by the SwordLord DANG Tiled Exporter.
// It will get overwritten once you re-export your tile map!
// (c) 2019-2021 by SwordLord - the coding crew

// World ------------------------------------------------

static const dang::tmx_world level_1_world = {
    .width = 30,
    .height = 24,
    .tileWidth = 32,
    .tileHeight = 32
};

// Tilesets ------------------------------------------------

static const dang::tmx_tileset level_1_tilesets[] = {
    {"gfx_levels_castle_tiles", &gfx_levels_castle_tiles, 96,32,32,384,256,12,8},
    {"gfx_castle_decorations", &gfx_castle_decorations, 40,32,32,320,128,10,4},
    {"gfx_items", &gfx_items, 53,32,48,1696,48,53,1},
    {"gfx_bubbles", &gfx_bubbles, 11,32,32,352,32,11,1},
    {"hud_ui", &hud_ui, 105,16,16,240,112,15,7},
    {"gfx_king", &gfx_king, 27,32,32,864,32,27,1},
    {"gfx_pig", &gfx_pig, 34,32,32,1088,32,34,1},
    {"character_pigbomb", &character_pigbomb, 33,32,32,1056,32,33,1},
    {"character_pigcrate", &character_pigcrate, 39,32,32,1248,32,39,1},
};

static const size_t level_1_tilesets_len = 9;

// Animations ------------------------------------------------

static const dang::tmx_tileanimation level_1_tileanimations[] = {
    {"gfx_items",0,"coin_silver",{{0, 100},{1, 100},{2, 100},{3, 100}}},
    {"gfx_items",4,"coin_gold",{{4, 100},{5, 100},{6, 100},{7, 100}}},
    {"gfx_items",8,"coin_poof",{{8, 100},{9, 100},{10, 100},{11, 100}}},
    {"gfx_items",12,"gem_blue",{{12, 100},{13, 100},{14, 100},{15, 100}}},
    {"gfx_items",16,"gem_green",{{16, 100},{17, 100},{18, 100},{19, 100}}},
    {"gfx_items",20,"gem_red",{{20, 100},{21, 100},{22, 100},{23, 100}}},
    {"gfx_items",24,"gem_poof",{{24, 100},{25, 100},{26, 100},{27, 100}}},
    {"gfx_items",28,"potion_blue",{{28, 100},{29, 100},{30, 100},{31, 100},{32, 100},{33, 100},{34, 100}}},
    {"gfx_items",35,"potion_red",{{35, 100},{36, 100},{37, 100},{38, 100},{39, 100},{40, 100},{41, 100}}},
    {"gfx_items",42,"potion_green",{{42, 100},{43, 100},{44, 100},{45, 100},{46, 100},{47, 100},{48, 100}}},
    {"gfx_items",49,"potion_poof",{{49, 100},{50, 100},{51, 100},{52, 100}}},
    {"gfx_bubbles",0,"bubble_blow",{{0, 120},{1, 120},{2, 120},{3, 120},{4, 100}}},
    {"gfx_bubbles",4,"bubble_bobble",{{3, 120},{5, 120},{4, 120},{3, 120},{6, 120}}},
    {"gfx_bubbles",7,"bubble_poof",{{7, 100},{8, 100},{9, 100}}},
    {"gfx_king",0,"wait",{{0, 100},{1, 100},{2, 100},{3, 100},{4, 100},{5, 100},{6, 100},{0, 800}}},
    {"gfx_king",1,"blink",{{0, 100},{25, 100}}},
    {"gfx_king",7,"jump",{{9, 100},{7, 100}}},
    {"gfx_king",8,"on_air",{{8, 100}}},
    {"gfx_king",10,"walk",{{10, 100},{11, 100},{12, 100},{13, 100},{14, 100},{15, 100},{16, 100},{17, 100}}},
    {"gfx_king",18,"bubble",{{18, 100},{19, 100},{20, 100},{19, 100},{18, 100}}},
    {"gfx_king",21,"life_lost",{{21, 600},{22, 600},{23, 600}}},
    {"gfx_pig",0,"not_set",{{0, 100},{1, 100},{2, 100},{3, 100},{4, 100},{5, 100}}},
    {"gfx_pig",6,"sleeping",{{6, 100},{7, 100},{8, 100},{9, 100},{10, 100},{11, 100}}},
    {"gfx_pig",13,"bubbling",{{12, 100},{13, 100}}},
    {"gfx_pig",14,"loitering",{{14, 100},{15, 100},{16, 100},{17, 100},{18, 100}}},
    {"gfx_pig",24,"poof",{{24, 100},{25, 100},{26, 100},{27, 100},{28, 100},{29, 100},{30, 100},{31, 100},{32, 100},{33, 100}}},
    {"character_pigbomb",0,"picking_up",{{0, 100},{1, 100},{2, 100},{3, 100}}},
    {"character_pigbomb",4,"sleeping",{{4, 100},{5, 100},{6, 100},{7, 100},{8, 100},{9, 100},{10, 100},{11, 100},{12, 100},{13, 100}}},
    {"character_pigbomb",14,"loitering",{{14, 100},{15, 100},{16, 100},{17, 100},{18, 100},{19, 100}}},
    {"character_pigbomb",20,"throwing",{{20, 100},{21, 100},{22, 100},{23, 100},{24, 100}}},
    {"character_pigbomb",23,"bubbling",{{23, 100},{24, 100}}},
    {"character_pigbomb",25,"bomb_off",{{25, 100}}},
    {"character_pigbomb",26,"bomb_on",{{26, 100},{27, 100},{28, 100},{29, 100}}},
    {"character_pigbomb",31,"bubbling",{{31, 100},{32, 100}}},
    {"character_pigcrate",0,"picking_up",{{0, 100},{1, 100},{2, 100},{3, 100},{4, 100}}},
    {"character_pigcrate",5,"sleeping",{{5, 100},{6, 100},{7, 100},{8, 100},{9, 100},{10, 100},{11, 100},{12, 100},{13, 100}}},
    {"character_pigcrate",14,"loitering",{{14, 100},{15, 100},{16, 100},{17, 100},{18, 100},{19, 100}}},
    {"character_pigcrate",20,"throwing",{{20, 100},{21, 100},{22, 100},{23, 100},{24, 100},{36, 100}}},
    {"character_pigcrate",25,"looking_out",{{25, 100},{26, 100},{27, 100}}},
    {"character_pigcrate",28,"jumping",{{28, 100},{29, 100},{30, 100},{31, 100},{32, 100},{33, 100}}},
    {"character_pigcrate",37,"bubbling",{{37, 100},{38, 100}}},
};

static const size_t level_1_tileanimations_len = 41;

// Layers ------------------------------------------------

// layer tilelayer: lvl_1_bg
static const dang::tmx_tile level_1_lvl_1_bg_tiles[] = {

    {4, 0}, {25, 0}, {25, 0}, {25, 0}, {25, 0}, {25, 0}, {25, 0}, {5, 0}, {13, 0}, {13, 0}, {13, 0}, {13, 0}, {13, 0}, {4, 0}, {25, 0}, {25, 0}, {25, 0}, {25, 0}, {25, 0}, {5, 0}, {4, 0}, {25, 0}, {25, 0}, {25, 0}, {25, 0}, {25, 0}, {25, 0}, {25, 0}, {25, 0}, {5, 0},
    {14, 0}, {48, 0}, {49, 0}, {49, 0}, {49, 0}, {49, 0}, {50, 0}, {24, 0}, {25, 0}, {25, 0}, {25, 0}, {25, 0}, {18, 0}, {26, 0}, {48, 0}, {49, 0}, {49, 0}, {49, 0}, {50, 0}, {24, 0}, {26, 0}, {48, 0}, {49, 0}, {49, 0}, {49, 0}, {49, 0}, {49, 0}, {49, 0}, {50, 0}, {24, 0},
    {14, 0}, {60, 0}, {61, 0}, {61, 0}, {61, 0}, {61, 0}, {64, 0}, {76, 0}, {85, 0}, {85, 0}, {85, 0}, {83, 0}, {27, 0}, {48, 0}, {65, 0}, {61, 0}, {61, 0}, {61, 0}, {64, 0}, {49, 0}, {49, 0}, {65, 0}, {61, 0}, {61, 0}, {61, 0}, {61, 0}, {52, 0}, {73, 0}, {88, 0}, {85, 0},
    {14, 0}, {60, 0}, {61, 0}, {61, 0}, {61, 0}, {61, 0}, {61, 0}, {62, 0}, {0, 0}, {1, 0}, {2, 0}, {94, 0}, {77, 0}, {65, 0}, {61, 0}, {61, 0}, {61, 0}, {61, 0}, {61, 0}, {61, 0}, {61, 0}, {61, 0}, {61, 0}, {61, 0}, {61, 0}, {61, 0}, {62, 0}, {36, 0}, {37, 0}, {29, 0},
    {14, 0}, {60, 0}, {61, 0}, {61, 0}, {61, 0}, {61, 0}, {52, 0}, {74, 0}, {12, 0}, {13, 0}, {16, 0}, {2, 0}, {60, 0}, {61, 0}, {61, 0}, {52, 0}, {73, 0}, {73, 0}, {73, 0}, {73, 0}, {73, 0}, {73, 0}, {73, 0}, {73, 0}, {53, 0}, {61, 0}, {64, 0}, {49, 0}, {50, 0}, {12, 0},
    {14, 0}, {60, 0}, {61, 0}, {61, 0}, {61, 0}, {52, 0}, {74, 0}, {0, 0}, {17, 0}, {13, 0}, {13, 0}, {14, 0}, {60, 0}, {61, 0}, {52, 0}, {74, 0}, {0, 0}, {1, 0}, {1, 0}, {1, 0}, {1, 0}, {1, 0}, {1, 0}, {2, 0}, {72, 0}, {53, 0}, {61, 0}, {61, 0}, {62, 0}, {12, 0},
    {14, 0}, {72, 0}, {73, 0}, {73, 0}, {66, 0}, {74, 0}, {0, 0}, {17, 0}, {13, 0}, {13, 0}, {13, 0}, {14, 0}, {72, 0}, {73, 0}, {74, 0}, {0, 0}, {17, 0}, {13, 0}, {13, 0}, {13, 0}, {13, 0}, {13, 0}, {13, 0}, {16, 0}, {2, 0}, {72, 0}, {73, 0}, {73, 0}, {74, 0}, {12, 0},
    {16, 0}, {1, 0}, {1, 0}, {2, 0}, {63, 0}, {0, 0}, {17, 0}, {13, 0}, {13, 0}, {13, 0}, {13, 0}, {16, 0}, {1, 0}, {1, 0}, {1, 0}, {17, 0}, {13, 0}, {13, 0}, {13, 0}, {13, 0}, {13, 0}, {13, 0}, {13, 0}, {13, 0}, {16, 0}, {1, 0}, {1, 0}, {1, 0}, {1, 0}, {17, 0},
    {13, 0}, {13, 0}, {13, 0}, {14, 0}, {63, 0}, {12, 0}, {13, 0}, {13, 0}, {13, 0}, {13, 0}, {4, 0}, {25, 0}, {25, 0}, {25, 0}, {25, 0}, {25, 0}, {25, 0}, {25, 0}, {25, 0}, {5, 0}, {13, 0}, {13, 0}, {13, 0}, {13, 0}, {13, 0}, {13, 0}, {13, 0}, {13, 0}, {13, 0}, {13, 0},
    {4, 0}, {25, 0}, {25, 0}, {26, 0}, {63, 0}, {24, 0}, {25, 0}, {25, 0}, {5, 0}, {13, 0}, {14, 0}, {48, 0}, {49, 0}, {49, 0}, {49, 0}, {49, 0}, {49, 0}, {49, 0}, {50, 0}, {12, 0}, {13, 0}, {13, 0}, {13, 0}, {13, 0}, {13, 0}, {13, 0}, {13, 0}, {13, 0}, {13, 0}, {13, 0},
    {14, 0}, {48, 0}, {49, 0}, {49, 0}, {55, 0}, {49, 0}, {49, 0}, {50, 0}, {12, 0}, {13, 0}, {14, 0}, {72, 0}, {73, 0}, {53, 0}, {61, 0}, {61, 0}, {52, 0}, {73, 0}, {74, 0}, {12, 0}, {13, 0}, {13, 0}, {13, 0}, {13, 0}, {13, 0}, {13, 0}, {13, 0}, {13, 0}, {13, 0}, {13, 0},
    {14, 0}, {60, 0}, {61, 0}, {61, 0}, {61, 0}, {61, 0}, {61, 0}, {62, 0}, {12, 0}, {13, 0}, {19, 0}, {37, 0}, {38, 0}, {60, 0}, {61, 0}, {61, 0}, {62, 0}, {36, 0}, {37, 0}, {6, 0}, {25, 0}, {25, 0}, {25, 0}, {25, 0}, {25, 0}, {25, 0}, {25, 0}, {25, 0}, {25, 0}, {5, 0},
    {14, 0}, {60, 0}, {61, 0}, {61, 0}, {61, 0}, {61, 0}, {52, 0}, {74, 0}, {12, 0}, {13, 0}, {14, 0}, {84, 0}, {85, 0}, {54, 0}, {61, 0}, {61, 0}, {67, 0}, {85, 0}, {86, 0}, {12, 0}, {85, 0}, {85, 0}, {85, 0}, {85, 0}, {85, 0}, {85, 0}, {85, 0}, {77, 0}, {50, 0}, {12, 0},
    {14, 0}, {72, 0}, {73, 0}, {73, 0}, {73, 0}, {73, 0}, {74, 0}, {0, 0}, {17, 0}, {13, 0}, {40, 0}, {37, 0}, {38, 0}, {60, 0}, {61, 0}, {61, 0}, {62, 0}, {36, 0}, {37, 0}, {6, 0}, {37, 0}, {37, 0}, {37, 0}, {37, 0}, {37, 0}, {37, 0}, {38, 0}, {60, 0}, {62, 0}, {12, 0},
    {16, 0}, {1, 0}, {1, 0}, {1, 0}, {1, 0}, {1, 0}, {1, 0}, {17, 0}, {13, 0}, {13, 0}, {85, 0}, {85, 0}, {85, 0}, {89, 0}, {73, 0}, {73, 0}, {88, 0}, {85, 0}, {85, 0}, {12, 0}, {85, 0}, {85, 0}, {85, 0}, {85, 0}, {85, 0}, {85, 0}, {85, 0}, {89, 0}, {74, 0}, {12, 0},
    {13, 0}, {13, 0}, {13, 0}, {13, 0}, {13, 0}, {13, 0}, {13, 0}, {13, 0}, {13, 0}, {13, 0}, {1, 0}, {1, 0}, {1, 0}, {1, 0}, {1, 0}, {1, 0}, {1, 0}, {1, 0}, {1, 0}, {17, 0}, {1, 0}, {1, 0}, {1, 0}, {1, 0}, {1, 0}, {1, 0}, {1, 0}, {1, 0}, {1, 0}, {17, 0},
    {4, 0}, {25, 0}, {25, 0}, {25, 0}, {25, 0}, {25, 0}, {25, 0}, {25, 0}, {25, 0}, {25, 0}, {25, 0}, {25, 0}, {25, 0}, {25, 0}, {25, 0}, {25, 0}, {25, 0}, {5, 0}, {13, 0}, {13, 0}, {4, 0}, {25, 0}, {25, 0}, {5, 0}, {13, 0}, {4, 0}, {25, 0}, {25, 0}, {25, 0}, {25, 0},
    {14, 0}, {84, 0}, {85, 0}, {77, 0}, {49, 0}, {76, 0}, {85, 0}, {85, 0}, {85, 0}, {85, 0}, {85, 0}, {85, 0}, {77, 0}, {49, 0}, {49, 0}, {49, 0}, {50, 0}, {24, 0}, {25, 0}, {25, 0}, {26, 0}, {48, 0}, {50, 0}, {24, 0}, {25, 0}, {26, 0}, {48, 0}, {49, 0}, {76, 0}, {85, 0},
    {19, 0}, {37, 0}, {38, 0}, {60, 0}, {61, 0}, {62, 0}, {36, 0}, {37, 0}, {37, 0}, {29, 0}, {1, 0}, {2, 0}, {60, 0}, {61, 0}, {61, 0}, {61, 0}, {64, 0}, {76, 0}, {85, 0}, {85, 0}, {85, 0}, {89, 0}, {88, 0}, {85, 0}, {85, 0}, {85, 0}, {54, 0}, {61, 0}, {62, 0}, {0, 0},
    {14, 0}, {48, 0}, {49, 0}, {65, 0}, {61, 0}, {64, 0}, {49, 0}, {49, 0}, {50, 0}, {30, 0}, {25, 0}, {26, 0}, {60, 0}, {61, 0}, {61, 0}, {61, 0}, {61, 0}, {62, 0}, {36, 0}, {29, 0}, {28, 0}, {37, 0}, {37, 0}, {37, 0}, {37, 0}, {38, 0}, {60, 0}, {61, 0}, {62, 0}, {12, 0},
    {26, 0}, {60, 0}, {61, 0}, {61, 0}, {61, 0}, {61, 0}, {61, 0}, {61, 0}, {62, 0}, {15, 0}, {85, 0}, {77, 0}, {65, 0}, {52, 0}, {73, 0}, {73, 0}, {53, 0}, {64, 0}, {50, 0}, {12, 0}, {14, 0}, {48, 0}, {49, 0}, {49, 0}, {49, 0}, {49, 0}, {65, 0}, {61, 0}, {62, 0}, {12, 0},
    {85, 0}, {89, 0}, {53, 0}, {61, 0}, {61, 0}, {61, 0}, {61, 0}, {52, 0}, {74, 0}, {42, 0}, {2, 0}, {60, 0}, {61, 0}, {62, 0}, {0, 0}, {2, 0}, {60, 0}, {61, 0}, {62, 0}, {12, 0}, {14, 0}, {60, 0}, {61, 0}, {61, 0}, {61, 0}, {61, 0}, {61, 0}, {61, 0}, {62, 0}, {12, 0},
    {1, 0}, {2, 0}, {72, 0}, {73, 0}, {73, 0}, {73, 0}, {73, 0}, {74, 0}, {0, 0}, {17, 0}, {14, 0}, {72, 0}, {73, 0}, {74, 0}, {12, 0}, {14, 0}, {72, 0}, {73, 0}, {74, 0}, {12, 0}, {14, 0}, {72, 0}, {73, 0}, {73, 0}, {73, 0}, {73, 0}, {73, 0}, {73, 0}, {74, 0}, {12, 0},
    {13, 0}, {16, 0}, {1, 0}, {1, 0}, {1, 0}, {1, 0}, {1, 0}, {1, 0}, {17, 0}, {13, 0}, {16, 0}, {1, 0}, {1, 0}, {1, 0}, {17, 0}, {16, 0}, {1, 0}, {1, 0}, {1, 0}, {17, 0}, {16, 0}, {1, 0}, {1, 0}, {1, 0}, {1, 0}, {1, 0}, {1, 0}, {1, 0}, {1, 0}, {17, 0}

};

static const size_t level_1_lvl_1_bg_tiles_len = 720;

static const dang::tmx_layer level_1_lvl_1_bg = {
    .name = "lvl_1_bg",
    .type = dang::tmx_layerType::ltTile,
    .opacity = 1,
    .visible = true,
    .z_order = 0,
    .tl_width = 30,
    .tl_height = 24,
    .tl_tileset = "gfx_levels_castle_tiles",
    .tl_tiles = level_1_lvl_1_bg_tiles,
    .tl_tiles_len = level_1_lvl_1_bg_tiles_len,
    .spriteobjects = nullptr,
    .spriteobejcts_len = 0
};

// Objects for layer: lvl_1_mood
static const dang::tmx_spriteobject level_1_lvl_1_mood_objects[] = {

    {3,"3","",61,654,32,32,true,"gfx_castle_decorations",20,""},
    {4,"4","",61,622,32,32,true,"gfx_castle_decorations",0,""},
    {5,"5","",238,623,32,32,true,"gfx_castle_decorations",21,""},
    {6,"6","",270,623,32,32,true,"gfx_castle_decorations",22,""},
    {7,"7","",238,655,32,32,true,"gfx_castle_decorations",31,""},
    {8,"8","",270,655,32,32,true,"gfx_castle_decorations",32,""},
    {64,"64","",166,134,32,32,true,"gfx_castle_decorations",21,""},
    {65,"65","",198,134,32,32,true,"gfx_castle_decorations",22,""},
    {66,"66","",166,166,32,32,true,"gfx_castle_decorations",31,""},
    {67,"67","",198,166,32,32,true,"gfx_castle_decorations",32,""},
    {86,"86","",399,625,32,32,true,"gfx_castle_decorations",0,""},
    {87,"87","",528,624,32,32,true,"gfx_castle_decorations",0,""},
    {88,"88","",399,657,32,32,true,"gfx_castle_decorations",30,""},
    {89,"89","",528,656,32,32,true,"gfx_castle_decorations",30,""},
    {98,"98","",448,553,32,32,true,"gfx_castle_decorations",23,""},
    {99,"99","",480,553,32,32,true,"gfx_castle_decorations",24,""},
    {100,"100","",448,585,32,32,true,"gfx_castle_decorations",33,""},
    {101,"101","",480,585,32,32,true,"gfx_castle_decorations",34,""},
    {121,"121","",460,307,32,32,true,"gfx_castle_decorations",21,""},
    {122,"122","",492,307,32,32,true,"gfx_castle_decorations",22,""},
    {123,"123","",460,339,32,32,true,"gfx_castle_decorations",31,""},
    {124,"124","",492,339,32,32,true,"gfx_castle_decorations",32,""},
    {129,"129","",460,400,32,32,true,"gfx_castle_decorations",23,""},
    {130,"130","",492,400,32,32,true,"gfx_castle_decorations",24,""},
    {131,"131","",460,432,32,32,true,"gfx_castle_decorations",33,""},
    {133,"133","",492,432,32,32,true,"gfx_castle_decorations",34,""},
    {134,"134","",64,328,32,32,true,"gfx_castle_decorations",0,""},
    {135,"135","",64,360,32,32,true,"gfx_castle_decorations",10,""},
    {136,"136","",64,392,32,32,true,"gfx_castle_decorations",20,""},
    {137,"137","",192,326,32,32,true,"gfx_castle_decorations",0,""},
    {138,"138","",192,358,32,32,true,"gfx_castle_decorations",10,""},
    {139,"139","",192,390,32,32,true,"gfx_castle_decorations",20,""},
    {52,"52","",160,672,32,32,true,"gfx_castle_decorations",1,""},
    {53,"53","",192,672,32,32,true,"gfx_castle_decorations",3,""},
    {47,"47","",128,576,32,32,true,"gfx_castle_decorations",4,""},
    {50,"50","",128,640,32,32,true,"gfx_castle_decorations",4,""},
    {51,"51","",128,608,32,32,true,"gfx_castle_decorations",4,""},
    {232,"232","",128,704,32,32,true,"gfx_castle_decorations",1,""},
    {233,"233","",160,704,32,32,true,"gfx_castle_decorations",2,""},
    {234,"234","",192,704,32,32,true,"gfx_castle_decorations",3,""},
    {255,"255","",864,576,32,32,true,"gfx_castle_decorations",0,""},
    {256,"256","",864,608,32,32,true,"gfx_castle_decorations",10,""},
    {257,"257","",864,640,32,32,true,"gfx_castle_decorations",10,""},
    {258,"258","",864,672,32,32,true,"gfx_castle_decorations",20,""},
    {259,"259","",832,608,32,32,true,"gfx_castle_decorations",4,""},
    {260,"260","",832,640,32,32,true,"gfx_castle_decorations",4,""},
    {261,"261","",896,608,32,32,true,"gfx_castle_decorations",4,""},
    {262,"262","",896,640,32,32,true,"gfx_castle_decorations",4,""},
    {263,"263","",896,672,32,32,true,"gfx_castle_decorations",4,""},
    {264,"264","",896,704,32,32,true,"gfx_castle_decorations",4,""},
    {278,"278","",704,672,32,32,true,"gfx_castle_decorations",5,""},
    {279,"279","",768,672,32,32,true,"gfx_castle_decorations",5,""},
    {82,"82","",384,576,32,32,true,"gfx_castle_decorations",4,""},
    {83,"83","",544,608,32,32,true,"gfx_castle_decorations",4,""},
    {84,"84","",544,704,32,32,true,"gfx_castle_decorations",4,""},
    {85,"85","",384,704,32,32,true,"gfx_castle_decorations",4,""},
    {102,"102","",448,608,32,32,true,"gfx_castle_decorations",1,""},
    {103,"103","",448,640,32,32,true,"gfx_castle_decorations",1,""},
    {104,"104","",480,608,32,32,true,"gfx_castle_decorations",3,""},
    {105,"105","",480,640,32,32,true,"gfx_castle_decorations",3,""},
    {329,"329","hotrect_platform",352,96,32,4,true,"",0,""},
    {170,"170","",800,128,32,32,true,"gfx_castle_decorations",4,""},
    {117,"117","",416,352,32,32,true,"gfx_castle_decorations",4,""},
    {118,"118","",416,416,32,32,true,"gfx_castle_decorations",4,""},
    {119,"119","",512,416,32,32,true,"gfx_castle_decorations",4,""},
    {120,"120","",512,352,32,32,true,"gfx_castle_decorations",4,""},
    {112,"112","",480,384,32,32,true,"gfx_castle_decorations",3,""},
    {113,"113","",480,448,32,32,true,"gfx_castle_decorations",3,""},
    {108,"108","",448,448,32,32,true,"gfx_castle_decorations",1,""},
    {109,"109","",448,384,32,32,true,"gfx_castle_decorations",1,""},
    {71,"71","",32,384,32,32,true,"gfx_castle_decorations",4,""},
    {72,"72","",224,352,32,32,true,"gfx_castle_decorations",4,""},
    {73,"73","",96,352,32,32,true,"gfx_castle_decorations",1,""},
    {74,"74","",96,384,32,32,true,"gfx_castle_decorations",1,""},
    {75,"75","",96,416,32,32,true,"gfx_castle_decorations",1,""},
    {76,"76","",160,352,32,32,true,"gfx_castle_decorations",3,""},
    {77,"77","",160,384,32,32,true,"gfx_castle_decorations",3,""},
    {78,"78","",160,416,32,32,true,"gfx_castle_decorations",3,""},
    {79,"79","",128,416,32,32,true,"gfx_castle_decorations",2,""},
    {80,"80","",128,384,32,32,true,"gfx_castle_decorations",2,""},
    {81,"81","",128,352,32,32,true,"gfx_castle_decorations",2,""},
    {54,"54","",96,192,32,32,true,"gfx_castle_decorations",4,""},
    {55,"55","",64,160,32,32,true,"gfx_castle_decorations",4,""},
    {56,"56","",96,128,32,32,true,"gfx_castle_decorations",4,""},
    {57,"57","",64,96,32,32,true,"gfx_castle_decorations",4,""},
    {58,"58","",96,64,32,32,true,"gfx_castle_decorations",1,""},
    {59,"59","",128,64,32,32,true,"gfx_castle_decorations",3,""},
    {62,"62","",192,96,32,32,true,"gfx_castle_decorations",11,""},
    {63,"63","",224,96,32,32,true,"gfx_castle_decorations",13,""},
    {165,"165","",384,192,32,32,true,"gfx_castle_decorations",4,""},
    {166,"166","",832,192,32,32,true,"gfx_castle_decorations",1,""},
    {167,"167","",864,192,32,32,true,"gfx_castle_decorations",3,""},
    {168,"168","",448,160,32,32,true,"gfx_castle_decorations",3,""},
    {169,"169","",416,160,32,32,true,"gfx_castle_decorations",1,""},
    {164,"164","",448,64,32,32,true,"gfx_castle_decorations",4,""},
    {328,"328","",352,96,32,32,true,"gfx_castle_decorations",4,""},
    {373,"373","",864,440,32,32,true,"gfx_castle_decorations",4,""},
    {378,"378","",416,64,32,32,true,"gfx_castle_decorations",4,""},
    {115,"115","",384,320,32,32,true,"gfx_castle_decorations",3,""},
    {110,"110","",352,320,32,32,true,"gfx_castle_decorations",1,""},
    {111,"111","",544,320,32,32,true,"gfx_castle_decorations",1,""},
    {114,"114","",576,320,32,32,true,"gfx_castle_decorations",3,""}

};

static const size_t level_1_lvl_1_mood_objects_len = 102;

static const dang::tmx_layer level_1_lvl_1_mood = {
    .name = "lvl_1_mood",
    .type = dang::tmx_layerType::ltObjects,
    .opacity = 1,
    .visible = true,
    .z_order = 1,
    .tl_width = 0,
    .tl_height = 0,
    .tl_tileset = "",
    .tl_tiles = nullptr,
    .tl_tiles_len = 0,
    .spriteobjects = level_1_lvl_1_mood_objects,
    .spriteobejcts_len = level_1_lvl_1_mood_objects_len
};

// Objects for layer: lvl_1_obj
static const dang::tmx_spriteobject level_1_lvl_1_obj_objects[] = {

    {143,"143","coin_silver",384,534,32,48,true,"gfx_items",0,""},
    {144,"144","coin_silver",448,598,32,48,true,"gfx_items",0,""},
    {145,"145","coin_silver",480,598,32,48,true,"gfx_items",0,""},
    {146,"146","coin_silver",544,662,32,48,true,"gfx_items",0,""},
    {147,"147","coin_silver",384,662,32,48,true,"gfx_items",0,""},
    {148,"148","coin_silver",128,598,32,48,true,"gfx_items",0,""},
    {149,"149","coin_silver",128,566,32,48,true,"gfx_items",0,""},
    {150,"150","coin_silver",128,534,32,48,true,"gfx_items",0,""},
    {151,"151","coin_silver",352,310,32,48,true,"gfx_items",0,""},
    {152,"152","coin_silver",384,310,32,48,true,"gfx_items",0,""},
    {153,"153","coin_silver",544,310,32,48,true,"gfx_items",0,""},
    {154,"154","coin_silver",576,310,32,48,true,"gfx_items",0,""},
    {155,"155","coin_gold",352,374,32,48,true,"gfx_items",4,""},
    {156,"156","coin_gold",576,374,32,48,true,"gfx_items",4,""},
    {157,"157","coin_gold",544,566,32,48,true,"gfx_items",4,""},
    {158,"158","coin_gold",352,278,32,48,true,"gfx_items",4,""},
    {159,"159","coin_gold",384,278,32,48,true,"gfx_items",4,""},
    {160,"160","coin_gold",544,278,32,48,true,"gfx_items",4,""},
    {161,"161","coin_gold",576,278,32,48,true,"gfx_items",4,""},
    {162,"162","coin_gold",32,22,32,48,true,"gfx_items",4,""},
    {163,"163","gem_blue",463,321,32,48,true,"gfx_items",12,""},
    {179,"179","hotrect",0,704,64,64,true,"",0,""},
    {180,"180","hotrect_platform",128,704,96,4,true,"",0,""},
    {182,"182","hotrect",256,704,64,32,true,"",0,""},
    {183,"183","hotrect",0,32,32,640,true,"",0,""},
    {184,"184","hotrect",32,448,288,32,true,"",0,""},
    {185,"185","hotrect",32,576,64,32,true,"",0,""},
    {186,"186","hotrect",192,576,192,32,true,"",0,""},
    {187,"187","hotrect",288,608,32,96,true,"",0,""},
    {189,"189","hotrect_platform",128,576,32,4,true,"",0,""},
    {190,"190","hotrect_platform",128,608,32,4,true,"",0,""},
    {191,"191","hotrect_platform",128,640,32,4,true,"",0,""},
    {196,"196","king",0,672,32,32,true,"gfx_king",0,""},
    {197,"197","bubble_proto",128,480,32,32,true,"gfx_bubbles",0,""},
    {198,"198","hotrect_platform",160,672,64,4,true,"",0,""},
    {199,"199","coin_silver",64,694,32,48,true,"gfx_items",0,""},
    {200,"200","gem_blue",96,694,32,48,true,"gfx_items",12,""},
    {202,"202","potion_green",224,694,32,48,true,"gfx_items",42,""},
    {235,"235","hotrect",32,480,928,64,true,"",0,""},
    {236,"236","hotrect",64,736,896,32,true,"",0,""},
    {237,"237","hotrect",320,672,32,64,true,"",0,""},
    {238,"238","hotrect",320,608,64,32,true,"",0,""},
    {239,"239","hotrect",448,672,64,64,true,"",0,""},
    {240,"240","hotrect",608,288,32,192,true,"",0,""},
    {241,"241","hotrect",544,544,128,32,true,"",0,""},
    {243,"243","hotrect_platform",384,576,32,4,true,"",0,""},
    {244,"244","hotrect_platform",448,608,64,4,true,"",0,""},
    {245,"245","hotrect_platform",448,640,64,4,true,"",0,""},
    {246,"246","hotrect_platform",384,704,32,4,true,"",0,""},
    {247,"247","hotrect_platform",544,704,32,4,true,"",0,""},
    {248,"248","hotrect_platform",544,608,32,4,true,"",0,""},
    {280,"280","hotrect",736,544,96,32,true,"",0,""},
    {283,"283","hotrect",608,640,64,96,true,"",0,""},
    {284,"284","hotrect",928,576,32,160,true,"",0,""},
    {286,"286","hotrect",576,608,256,32,true,"",0,""},
    {288,"288","hotrect_platform",832,608,32,4,true,"",0,""},
    {289,"289","hotrect_platform",832,640,32,4,true,"",0,""},
    {290,"290","hotrect_platform",896,608,32,4,true,"",0,""},
    {291,"291","hotrect_platform",896,640,32,4,true,"",0,""},
    {292,"292","hotrect_platform",896,672,32,4,true,"",0,""},
    {293,"293","hotrect_platform",896,704,32,4,true,"",0,""},
    {265,"265","coin_silver",672,566,32,48,true,"gfx_items",0,""},
    {266,"266","coin_silver",704,566,32,48,true,"gfx_items",0,""},
    {267,"267","coin_silver",672,534,32,48,true,"gfx_items",0,""},
    {268,"268","coin_silver",704,534,32,48,true,"gfx_items",0,""},
    {269,"269","coin_gold",672,630,32,48,true,"gfx_items",4,""},
    {270,"270","coin_silver",704,630,32,48,true,"gfx_items",0,""},
    {271,"271","coin_silver",736,630,32,48,true,"gfx_items",0,""},
    {272,"272","coin_silver",768,630,32,48,true,"gfx_items",0,""},
    {273,"273","coin_silver",800,630,32,48,true,"gfx_items",0,""},
    {274,"274","coin_silver",832,534,32,48,true,"gfx_items",0,""},
    {275,"275","coin_silver",864,534,32,48,true,"gfx_items",0,""},
    {276,"276","coin_silver",896,534,32,48,true,"gfx_items",0,""},
    {277,"277","coin_silver",928,534,32,48,true,"gfx_items",0,""},
    {294,"294","hotrect_platform",416,416,32,4,true,"",0,""},
    {295,"295","hotrect_platform",416,352,32,4,true,"",0,""},
    {296,"296","hotrect_platform",512,352,32,4,true,"",0,""},
    {297,"297","hotrect_platform",512,416,32,4,true,"",0,""},
    {298,"298","hotrect_platform",448,384,64,4,true,"",0,""},
    {299,"299","hotrect_platform",448,448,64,4,true,"",0,""},
    {300,"300","hotrect_platform",352,320,64,4,true,"",0,""},
    {301,"301","hotrect_platform",544,320,64,4,true,"",0,""},
    {305,"305","hotrect",256,288,96,160,true,"",0,""},
    {306,"306","hotrect",352,416,64,32,true,"",0,""},
    {307,"307","hotrect",352,352,64,32,true,"",0,""},
    {308,"308","hotrect",544,352,384,32,true,"",0,""},
    {309,"309","hotrect",544,416,320,32,true,"",0,""},
    {310,"310","hotrect",512,160,256,32,true,"",0,""},
    {311,"311","hotrect",320,224,640,64,true,"",0,""},
    {312,"312","hotrect",520,192,280,32,true,"",0,""},
    {314,"314","hotrect",0,0,960,32,true,"",0,""},
    {315,"315","hotrect",608,32,64,32,true,"",0,""},
    {316,"316","hotrect",864,96,96,32,true,"",0,""},
    {317,"317","hotrect",928,32,32,32,true,"",0,""},
    {318,"318","hotrect",928,128,32,96,true,"",0,""},
    {319,"319","hotrect",352,128,32,96,true,"",0,""},
    {320,"320","hotrect_platform",384,192,32,4,true,"",0,""},
    {321,"321","hotrect_platform",416,160,64,4,true,"",0,""},
    {322,"322","hotrect_platform",832,192,64,4,true,"",0,""},
    {323,"323","hotrect_platform",800,128,32,4,true,"",0,""},
    {324,"324","hotrect_platform",384,64,96,4,true,"",0,""},
    {326,"326","hotrect",256,100,96,60,true,"",0,""},
    {330,"330","hotrect",384,68,32,28,true,"",0,""},
    {331,"331","hotrect",224,32,128,32,true,"",0,""},
    {333,"dan","pig_box",320,640,32,32,true,"character_pigcrate",5,""},
    {334,"334","pig_bomb",768,704,32,32,true,"character_pigbomb",4,""},
    {335,"335","pig_normal",576,704,32,32,true,"gfx_pig",0,""},
    {336,"336","pig_normal",800,576,32,32,true,"gfx_pig",0,""},
    {340,"boris","pig_box",480,640,32,32,true,"character_pigcrate",5,""},
    {341,"fred","pig_bomb",192,544,32,32,true,"character_pigbomb",4,"insanity"},
    {342,"sam","pig_normal",192,672,32,32,true,"gfx_pig",0,"berserk"},
    {344,"344","crate_proto",32,480,32,32,true,"character_pigcrate",34,""},
    {345,"345","hotrect",-8,648,8,64,true,"",0,""},
    {346,"346","hotrect",960,32,8,560,true,"",0,""},
    {347,"1","room_trigger",317,544,2,32,true,"",0,""},
    {348,"0","room_trigger",288,544,2,32,true,"",0,""},
    {349,"2","room_trigger",640,576,2,32,true,"",0,""},
    {350,"1","room_trigger",608,576,2,32,true,"",0,""},
    {351,"351","bomb_proto",64,480,32,32,true,"character_pigbomb",26,""},
    {352,"352","pigpoof_proto",96,480,32,32,true,"gfx_pig",24,""},
    {353,"3","warp_room_trigger",958,544,2,32,true,"",0,""},
    {354,"354","hotrect",32,224,96,96,true,"",0,""},
    {355,"355","hotrect",224,416,32,32,true,"",0,""},
    {356,"356","hotrect",160,224,96,96,true,"",0,""},
    {357,"357","hotrect",192,192,64,32,true,"",0,""},
    {358,"358","hotrect",224,160,64,32,true,"",0,""},
    {360,"360","hotrect_platform",96,64,64,4,true,"",0,""},
    {361,"361","hotrect_platform",64,96,32,4,true,"",0,""},
    {362,"362","hotrect_platform",96,128,32,4,true,"",0,""},
    {363,"363","hotrect_platform",64,160,32,4,true,"",0,""},
    {364,"364","hotrect_platform",96,192,32,4,true,"",0,""},
    {365,"365","hotrect",192,96,160,12,true,"",0,""},
    {366,"366","hotrect_platform",96,352,96,4,true,"",0,""},
    {367,"367","hotrect_platform",96,384,96,4,true,"",0,""},
    {368,"368","hotrect_platform",96,416,96,4,true,"",0,""},
    {369,"369","hotrect_platform",32,384,32,4,true,"",0,""},
    {370,"370","hotrect_platform",224,352,32,4,true,"",0,""},
    {371,"3","warp_room_trigger",957,64,2,32,true,"",0,""},
    {372,"372","hotrect_platform",352,96,32,4,true,"",0,""},
    {374,"374","hotrect",928,352,32,128,true,"",0,""},
    {375,"375","hotrect_platform",864,440,32,4,true,"",0,""},
    {376,"2","warp_room_trigger",640,448,2,32,true,"",0,""},
    {377,"4","warp_room_trigger",640,384,2,32,true,"",0,""},
    {379,"7","warp_room_trigger",517,192,2,32,true,"",0,""},
    {380,"4","warp_room_trigger",320,448,2,32,true,"",0,""},
    {381,"5","room_trigger",288,64,2,32,true,"",0,""},
    {382,"4","room_trigger",320,64,2,32,true,"",0,""},
    {383,"5","warp_room_trigger",128,288,32,2,true,"",0,""},
    {384,"6","warp_room_trigger",128,247,32,2,true,"",0,""},
    {385,"385","hotrect",480,192,40,4,true,"",0,""}

};

static const size_t level_1_lvl_1_obj_objects_len = 150;

static const dang::tmx_layer level_1_lvl_1_obj = {
    .name = "lvl_1_obj",
    .type = dang::tmx_layerType::ltObjects,
    .opacity = 1,
    .visible = true,
    .z_order = 2,
    .tl_width = 0,
    .tl_height = 0,
    .tl_tileset = "",
    .tl_tiles = nullptr,
    .tl_tiles_len = 0,
    .spriteobjects = level_1_lvl_1_obj_objects,
    .spriteobejcts_len = level_1_lvl_1_obj_objects_len
};

// Objects for layer: lvl_1_fg
static const dang::tmx_spriteobject level_1_lvl_1_fg_objects[] = {

    {386,"386","",352,32,32,32,true,"gfx_levels_castle_tiles",25,""},
    {387,"387","",384,32,32,32,true,"gfx_levels_castle_tiles",18,""},
    {389,"389","",416,32,32,32,true,"gfx_levels_castle_tiles",26,""},
    {390,"390","",480,192,32,32,true,"gfx_levels_castle_tiles",0,""},
    {391,"391","",512,192,32,32,true,"gfx_levels_castle_tiles",17,""},
    {395,"395","",416,0,32,32,true,"gfx_levels_castle_tiles",13,""},
    {396,"396","",384,0,32,32,true,"gfx_levels_castle_tiles",13,""},
    {397,"397","",352,0,32,32,true,"gfx_levels_castle_tiles",13,""},
    {398,"398","",416,0,32,32,true,"gfx_levels_castle_tiles",4,""}

};

static const size_t level_1_lvl_1_fg_objects_len = 9;

static const dang::tmx_layer level_1_lvl_1_fg = {
    .name = "lvl_1_fg",
    .type = dang::tmx_layerType::ltObjects,
    .opacity = 1,
    .visible = true,
    .z_order = 3,
    .tl_width = 0,
    .tl_height = 0,
    .tl_tileset = "",
    .tl_tiles = nullptr,
    .tl_tiles_len = 0,
    .spriteobjects = level_1_lvl_1_fg_objects,
    .spriteobejcts_len = level_1_lvl_1_fg_objects_len
};

// Objects for layer: lvl_1_hud
static const dang::tmx_spriteobject level_1_lvl_1_hud_objects[] = {

    {250,"250","",15,18,32,32,true,"gfx_king",26,""},
    {251,"251","",46,37,16,16,true,"hud_ui",61,""},
    {252,"252","",62,37,16,16,true,"hud_ui",62,""},
    {254,"254","",78,37,16,16,true,"hud_ui",63,""}

};

static const size_t level_1_lvl_1_hud_objects_len = 4;

static const dang::tmx_layer level_1_lvl_1_hud = {
    .name = "lvl_1_hud",
    .type = dang::tmx_layerType::ltObjects,
    .opacity = 1,
    .visible = true,
    .z_order = 4,
    .tl_width = 0,
    .tl_height = 0,
    .tl_tileset = "",
    .tl_tiles = nullptr,
    .tl_tiles_len = 0,
    .spriteobjects = level_1_lvl_1_hud_objects,
    .spriteobejcts_len = level_1_lvl_1_hud_objects_len
};

// layer with points - path layer
static const dang::tmx_waypoint level_1_waypoints[] = {
    {408, 16,703, 0},
    {409, 48,703, 0},
    {410, 80,735, 0},
    {411, 112,735, 0},
    {412, 240,735, 0},
    {413, 208,703, 0},
    {414, 144,703, 0},
    {415, 272,703, 0},
    {416, 208,575, },
    {417, 272,575, },
};

static const size_t level_1_waypoints_len = 10;

static const dang::tmx_waypoint_connection level_1_connections[] = {
    {408, 409, 0x1},
    {409, 408, 0x1},
    {409, 410, 0x1},
    {410, 411, 0x1},
    {410, 409, 0x2},
    {411, 410, 0x1},
    {411, 412, 0x1},
    {411, 414, 0x2},
    {412, 411, 0x1},
    {412, 413, 0x2},
    {412, 415, 0x2},
    {413, 414, 0x1},
    {413, 412, 0x1},
    {414, 411, 0x1},
    {414, 413, 0x1},
    {415, 412, 0x1},
    {416, 417, 0x1},
    {417, 416, 0x1},
};

static const size_t level_1_connections_len = 18;

const static dang::tmx_layer level_1_layers[] = {
    level_1_lvl_1_bg,
    level_1_lvl_1_mood,
    level_1_lvl_1_obj,
    level_1_lvl_1_fg,
    level_1_lvl_1_hud,
};

const static size_t level_1_layers_len = 6;

// Level ---------------------------------------------------

static const dang::tmx_level level_1_level {
    .w = &level_1_world,
    .tilesets = level_1_tilesets,
    .tilesets_len = level_1_tilesets_len,
    .tileanimations = level_1_tileanimations,
    .tileanimations_len = level_1_tileanimations_len,
    .layers = level_1_layers,
    .layers_len = level_1_layers_len,
    .waypoints = level_1_waypoints,
    .waypoints_len = level_1_waypoints_len,
    .waypoint_connections = level_1_connections,
    .waypoint_connections_len = level_1_connections_len
};


