// This file is auto generated by the SwordLord DANG Tiled Exporter.
// It will get overwritten once you re-export your tile map!
// (c) 2019-2021 by SwordLord - the coding crew

// World ------------------------------------------------

static const dang::tmx_world prefs_1_world = {
    .width = 10,
    .height = 8,
    .tileWidth = 32,
    .tileHeight = 32
};

// Tilesets ------------------------------------------------

static const dang::tmx_tileset prefs_1_tilesets[] = {
    {"gfx_levels_castle_tiles", &gfx_levels_castle_tiles, 96,32,32,384,256,12,8},
    {"hud_ui", &hud_ui, 105,16,16,240,112,15,7},
};

static const size_t prefs_1_tilesets_len = 2;

// Animations ------------------------------------------------

static const dang::tmx_tileanimation prefs_1_tileanimations[] = {
};

static const size_t prefs_1_tileanimations_len = 0;

// Layers ------------------------------------------------

// layer tilelayer: prefs_bg
static const dang::tmx_tile prefs_1_prefs_bg_tiles[] = {

    {4, 0}, {25, 0}, {25, 0}, {25, 0}, {25, 0}, {25, 0}, {25, 0}, {25, 0}, {25, 0}, {5, 0},
    {14, 0}, {48, 0}, {49, 0}, {49, 0}, {49, 0}, {49, 0}, {49, 0}, {49, 0}, {50, 0}, {12, 0},
    {14, 0}, {60, 0}, {61, 0}, {61, 0}, {61, 0}, {61, 0}, {61, 0}, {61, 0}, {62, 0}, {12, 0},
    {14, 0}, {60, 0}, {61, 0}, {61, 0}, {61, 0}, {61, 0}, {61, 0}, {61, 0}, {62, 0}, {12, 0},
    {16, 0}, {1, 0}, {1, 0}, {1, 0}, {1, 0}, {1, 0}, {1, 0}, {1, 0}, {1, 0}, {17, 0},
    {13, 0}, {13, 0}, {13, 0}, {13, 0}, {13, 0}, {13, 0}, {13, 0}, {13, 0}, {13, 0}, {13, 0},
    {13, 0}, {13, 0}, {13, 0}, {13, 0}, {13, 0}, {13, 0}, {13, 0}, {13, 0}, {13, 0}, {13, 0},
    {13, 0}, {13, 0}, {13, 0}, {13, 0}, {13, 0}, {13, 0}, {13, 0}, {13, 0}, {13, 0}, {13, 0}

};

static const size_t prefs_1_prefs_bg_tiles_len = 80;

static const dang::tmx_layer prefs_1_prefs_bg = {
    .name = "prefs_bg",
    .type = dang::tmx_layerType::ltTile,
    .opacity = 1,
    .visible = true,
    .z_order = 0,
    .position = {0,0},
    .tl_width = 10,
    .tl_height = 8,
    .tl_tileset = "gfx_levels_castle_tiles",
    .tl_tiles = prefs_1_prefs_bg_tiles,
    .tl_tiles_len = prefs_1_prefs_bg_tiles_len,
    .spriteobjects = nullptr,
    .spriteobejcts_len = 0
};

// Objects for layer: prefs_decoration
static const dang::tmx_spriteobject prefs_1_prefs_decoration_objects[] = {

    {166,"166","",8,147,16,16,true,"hud_ui",20,"",0,0b0000},
    {167,"167","",8,179,16,16,true,"hud_ui",35,"",0,0b0000},
    {168,"168","",8,195,16,16,true,"hud_ui",35,"",0,0b0000},
    {171,"171","",8,211,16,16,true,"hud_ui",50,"",0,0b0000},
    {172,"172","",296,211,16,16,true,"hud_ui",52,"",0,0b0000},
    {175,"175","",296,195,16,16,true,"hud_ui",37,"",0,0b0000},
    {176,"176","",296,179,16,16,true,"hud_ui",37,"",0,0b0000},
    {177,"177","",296,147,16,16,true,"hud_ui",22,"",0,0b0000},
    {178,"178","",280,147,16,16,true,"hud_ui",21,"",0,0b0000},
    {179,"179","",280,179,16,16,true,"hud_ui",36,"",0,0b0000},
    {180,"180","",280,195,16,16,true,"hud_ui",36,"",0,0b0000},
    {183,"183","",280,211,16,16,true,"hud_ui",51,"",0,0b0000},
    {184,"184","",264,147,16,16,true,"hud_ui",21,"",0,0b0000},
    {185,"185","",264,179,16,16,true,"hud_ui",36,"",0,0b0000},
    {186,"186","",264,195,16,16,true,"hud_ui",36,"",0,0b0000},
    {189,"189","",264,211,16,16,true,"hud_ui",51,"",0,0b0000},
    {190,"190","",248,147,16,16,true,"hud_ui",21,"",0,0b0000},
    {191,"191","",248,179,16,16,true,"hud_ui",36,"",0,0b0000},
    {192,"192","",248,195,16,16,true,"hud_ui",36,"",0,0b0000},
    {195,"195","",248,211,16,16,true,"hud_ui",51,"",0,0b0000},
    {196,"196","",232,147,16,16,true,"hud_ui",21,"",0,0b0000},
    {197,"197","",232,179,16,16,true,"hud_ui",36,"",0,0b0000},
    {198,"198","",232,195,16,16,true,"hud_ui",36,"",0,0b0000},
    {201,"201","",232,211,16,16,true,"hud_ui",51,"",0,0b0000},
    {202,"202","",216,147,16,16,true,"hud_ui",21,"",0,0b0000},
    {203,"203","",216,179,16,16,true,"hud_ui",36,"",0,0b0000},
    {204,"204","",216,195,16,16,true,"hud_ui",36,"",0,0b0000},
    {207,"207","",216,211,16,16,true,"hud_ui",51,"",0,0b0000},
    {208,"208","",200,147,16,16,true,"hud_ui",21,"",0,0b0000},
    {209,"209","",200,179,16,16,true,"hud_ui",36,"",0,0b0000},
    {210,"210","",200,195,16,16,true,"hud_ui",36,"",0,0b0000},
    {213,"213","",200,211,16,16,true,"hud_ui",51,"",0,0b0000},
    {214,"214","",184,147,16,16,true,"hud_ui",21,"",0,0b0000},
    {215,"215","",184,179,16,16,true,"hud_ui",36,"",0,0b0000},
    {216,"216","",184,195,16,16,true,"hud_ui",36,"",0,0b0000},
    {219,"219","",184,211,16,16,true,"hud_ui",51,"",0,0b0000},
    {220,"220","",168,147,16,16,true,"hud_ui",21,"",0,0b0000},
    {221,"221","",168,179,16,16,true,"hud_ui",36,"",0,0b0000},
    {222,"222","",168,195,16,16,true,"hud_ui",36,"",0,0b0000},
    {225,"225","",168,211,16,16,true,"hud_ui",51,"",0,0b0000},
    {226,"226","",152,147,16,16,true,"hud_ui",21,"",0,0b0000},
    {227,"227","",152,179,16,16,true,"hud_ui",36,"",0,0b0000},
    {228,"228","",152,195,16,16,true,"hud_ui",36,"",0,0b0000},
    {231,"231","",152,211,16,16,true,"hud_ui",51,"",0,0b0000},
    {232,"232","",136,147,16,16,true,"hud_ui",21,"",0,0b0000},
    {233,"233","",136,179,16,16,true,"hud_ui",36,"",0,0b0000},
    {234,"234","",136,195,16,16,true,"hud_ui",36,"",0,0b0000},
    {237,"237","",136,211,16,16,true,"hud_ui",51,"",0,0b0000},
    {238,"238","",120,147,16,16,true,"hud_ui",21,"",0,0b0000},
    {239,"239","",120,179,16,16,true,"hud_ui",36,"",0,0b0000},
    {240,"240","",120,195,16,16,true,"hud_ui",36,"",0,0b0000},
    {243,"243","",120,211,16,16,true,"hud_ui",51,"",0,0b0000},
    {244,"244","",104,147,16,16,true,"hud_ui",21,"",0,0b0000},
    {245,"245","",104,179,16,16,true,"hud_ui",36,"",0,0b0000},
    {246,"246","",104,195,16,16,true,"hud_ui",36,"",0,0b0000},
    {249,"249","",104,211,16,16,true,"hud_ui",51,"",0,0b0000},
    {250,"250","",88,147,16,16,true,"hud_ui",21,"",0,0b0000},
    {251,"251","",88,179,16,16,true,"hud_ui",36,"",0,0b0000},
    {252,"252","",88,195,16,16,true,"hud_ui",36,"",0,0b0000},
    {255,"255","",88,211,16,16,true,"hud_ui",51,"",0,0b0000},
    {256,"256","",72,147,16,16,true,"hud_ui",21,"",0,0b0000},
    {257,"257","",72,179,16,16,true,"hud_ui",36,"",0,0b0000},
    {258,"258","",72,195,16,16,true,"hud_ui",36,"",0,0b0000},
    {261,"261","",72,211,16,16,true,"hud_ui",51,"",0,0b0000},
    {262,"262","",56,147,16,16,true,"hud_ui",21,"",0,0b0000},
    {263,"263","",56,179,16,16,true,"hud_ui",36,"",0,0b0000},
    {264,"264","",56,195,16,16,true,"hud_ui",36,"",0,0b0000},
    {267,"267","",56,211,16,16,true,"hud_ui",51,"",0,0b0000},
    {268,"268","",40,147,16,16,true,"hud_ui",21,"",0,0b0000},
    {269,"269","",40,179,16,16,true,"hud_ui",36,"",0,0b0000},
    {270,"270","",40,195,16,16,true,"hud_ui",36,"",0,0b0000},
    {273,"273","",40,211,16,16,true,"hud_ui",51,"",0,0b0000},
    {274,"274","",24,147,16,16,true,"hud_ui",21,"",0,0b0000},
    {275,"275","",24,179,16,16,true,"hud_ui",36,"",0,0b0000},
    {276,"276","",24,195,16,16,true,"hud_ui",36,"",0,0b0000},
    {279,"279","",24,211,16,16,true,"hud_ui",51,"",0,0b0000},
    {280,"280","",8,163,16,16,true,"hud_ui",35,"",0,0b0000},
    {281,"281","",296,163,16,16,true,"hud_ui",37,"",0,0b0000},
    {282,"282","",280,163,16,16,true,"hud_ui",36,"",0,0b0000},
    {283,"283","",264,163,16,16,true,"hud_ui",36,"",0,0b0000},
    {284,"284","",248,163,16,16,true,"hud_ui",36,"",0,0b0000},
    {285,"285","",232,163,16,16,true,"hud_ui",36,"",0,0b0000},
    {286,"286","",216,163,16,16,true,"hud_ui",36,"",0,0b0000},
    {287,"287","",200,163,16,16,true,"hud_ui",36,"",0,0b0000},
    {288,"288","",184,163,16,16,true,"hud_ui",36,"",0,0b0000},
    {289,"289","",168,163,16,16,true,"hud_ui",36,"",0,0b0000},
    {290,"290","",152,163,16,16,true,"hud_ui",36,"",0,0b0000},
    {291,"291","",136,163,16,16,true,"hud_ui",36,"",0,0b0000},
    {292,"292","",120,163,16,16,true,"hud_ui",36,"",0,0b0000},
    {293,"293","",104,163,16,16,true,"hud_ui",36,"",0,0b0000},
    {294,"294","",88,163,16,16,true,"hud_ui",36,"",0,0b0000},
    {295,"295","",72,163,16,16,true,"hud_ui",36,"",0,0b0000},
    {296,"296","",56,163,16,16,true,"hud_ui",36,"",0,0b0000},
    {297,"297","",40,163,16,16,true,"hud_ui",36,"",0,0b0000},
    {298,"298","",24,163,16,16,true,"hud_ui",36,"",0,0b0000}

};

static const size_t prefs_1_prefs_decoration_objects_len = 95;

static const dang::tmx_layer prefs_1_prefs_decoration = {
    .name = "prefs_decoration",
    .type = dang::tmx_layerType::ltObjects,
    .opacity = 1,
    .visible = true,
    .z_order = 1,
    .position = {0,0},
    .tl_width = 0,
    .tl_height = 0,
    .tl_tileset = "",
    .tl_tiles = nullptr,
    .tl_tiles_len = 0,
    .spriteobjects = prefs_1_prefs_decoration_objects,
    .spriteobejcts_len = prefs_1_prefs_decoration_objects_len
};

const static dang::tmx_layer prefs_1_layers[] = {
    prefs_1_prefs_bg,
    prefs_1_prefs_decoration,
};

const static size_t prefs_1_layers_len = 2;

// Level ---------------------------------------------------

static const dang::tmx_level prefs_1_level {
    .w = &prefs_1_world,
    .tilesets = prefs_1_tilesets,
    .tilesets_len = prefs_1_tilesets_len,
    .tileanimations = prefs_1_tileanimations,
    .tileanimations_len = prefs_1_tileanimations_len,
    .layers = prefs_1_layers,
    .layers_len = prefs_1_layers_len,
    .waypoints = nullptr,
    .waypoints_len = 0,
    .waypoint_connections = nullptr,
    .waypoint_connections_len = 0,
    .wavepoints = nullptr,
    .wavepoints_len = 0
};


