// This file is auto generated by the SwordLord DANG Tiled Exporter.
// It will get overwritten once you re-export your tile map!
// (c) 2019-2021 by SwordLord - the coding crew

// World ------------------------------------------------

static const dang::tmx_world prefs_1_world = {
    .width = 10,
    .height = 8,
    .tileWidth = 32,
    .tileHeight = 32
};

// Tilesets ------------------------------------------------

static const dang::tmx_tileset prefs_1_tilesets[] = {
    {"gfx_levels_castle_tiles", &gfx_levels_castle_tiles, 96,32,32,384,256,12,8},
    {"hud_ui", &hud_ui, 105,16,16,240,112,15,7},
};

static const size_t prefs_1_tilesets_len = 2;

// Animations ------------------------------------------------

static const dang::tmx_tileanimation prefs_1_tileanimations[] = {
};

static const size_t prefs_1_tileanimations_len = 0;

// Layers ------------------------------------------------

// layer tilelayer: prefs_bg
static const dang::tmx_tile prefs_1_prefs_bg_tiles[] = {

    {4, 0}, {25, 0}, {25, 0}, {25, 0}, {25, 0}, {25, 0}, {25, 0}, {25, 0}, {25, 0}, {5, 0},
    {14, 0}, {48, 0}, {49, 0}, {49, 0}, {49, 0}, {49, 0}, {49, 0}, {49, 0}, {50, 0}, {12, 0},
    {14, 0}, {60, 0}, {61, 0}, {61, 0}, {61, 0}, {61, 0}, {61, 0}, {61, 0}, {62, 0}, {12, 0},
    {14, 0}, {72, 0}, {73, 0}, {73, 0}, {73, 0}, {73, 0}, {73, 0}, {73, 0}, {74, 0}, {12, 0},
    {16, 0}, {1, 0}, {1, 0}, {1, 0}, {1, 0}, {1, 0}, {1, 0}, {1, 0}, {1, 0}, {17, 0},
    {13, 0}, {13, 0}, {13, 0}, {13, 0}, {13, 0}, {13, 0}, {13, 0}, {13, 0}, {13, 0}, {13, 0},
    {13, 0}, {13, 0}, {13, 0}, {13, 0}, {13, 0}, {13, 0}, {13, 0}, {13, 0}, {13, 0}, {13, 0},
    {13, 0}, {13, 0}, {13, 0}, {13, 0}, {13, 0}, {13, 0}, {13, 0}, {13, 0}, {13, 0}, {13, 0}

};

static const size_t prefs_1_prefs_bg_tiles_len = 80;

static const dang::tmx_layer prefs_1_prefs_bg = {
    .name = "prefs_bg",
    .type = dang::tmx_layerType::ltTile,
    .opacity = 1,
    .visible = true,
    .z_order = 0,
    .position = {0,0},
    .tl_width = 10,
    .tl_height = 8,
    .tl_tileset = "gfx_levels_castle_tiles",
    .tl_tiles = prefs_1_prefs_bg_tiles,
    .tl_tiles_len = prefs_1_prefs_bg_tiles_len,
    .spriteobjects = nullptr,
    .spriteobejcts_len = 0
};

const static dang::tmx_layer prefs_1_layers[] = {
    prefs_1_prefs_bg,
};

const static size_t prefs_1_layers_len = 2;

// Level ---------------------------------------------------

static const dang::tmx_level prefs_1_level {
    .w = &prefs_1_world,
    .tilesets = prefs_1_tilesets,
    .tilesets_len = prefs_1_tilesets_len,
    .tileanimations = prefs_1_tileanimations,
    .tileanimations_len = prefs_1_tileanimations_len,
    .layers = prefs_1_layers,
    .layers_len = prefs_1_layers_len,
    .waypoints = nullptr,
    .waypoints_len = 0,
    .waypoint_connections = nullptr,
    .waypoint_connections_len = 0,
    .wavepoints = nullptr,
    .wavepoints_len = 0,
    .zones = nullptr,
    .zones_len = 0,
    .zone_passages = nullptr,
    .zone_passages_len = 0
};


