// This file is auto generated by the SwordLord DANG Tiled Exporter.
// It will get overwritten once you re-export your tile map!
// (c) 2019-2021 by SwordLord - the coding crew


dang::tmx_level init_main_1() {

    dang::tmx_level lvl = {};

// World ------------------------------------------------

    lvl.w.width = 10;
    lvl.w.height = 8;
    lvl.w.tileWidth = 32;
    lvl.w.tileHeight = 32;

// Tilesets ------------------------------------------------

    // Tileset: gfx_levels_castle_tiles has ID: 0
    lvl.tilesets[0] = {"gfx_levels_castle_tiles",96,32,32,384,256,12,8};
    // Tileset: hud_ui has ID: 1
    lvl.tilesets[1] = {"hud_ui",105,16,16,240,112,15,7};
    // Tileset: main_pnk_logo has ID: 2
    lvl.tilesets[2] = {"main_pnk_logo",1,218,36,218,36,1,1};
    // Tileset: gfx_castle_decorations has ID: 3
    lvl.tilesets[3] = {"gfx_castle_decorations",40,32,32,320,128,10,4};
    // Tileset: gfx_king has ID: 4
    lvl.tilesets[4] = {"gfx_king",27,32,32,864,32,27,1};
    // Tileset: gfx_pig has ID: 5
    lvl.tilesets[5] = {"gfx_pig",34,32,32,1088,32,34,1};
    // Tileset: common_menus has ID: 6
    lvl.tilesets[6] = {"common_menus",3,58,32,58,96,1,3};

// Animations ------------------------------------------------

    // Animation: wait
    lvl.tileanimation["gfx_king_wait"] = {"gfx_king",0,"wait",{{0, 100},{1, 100},{2, 100},{3, 100},{4, 100},{5, 100},{6, 100},{0, 800}}};
    // Animation: blink
    lvl.tileanimation["gfx_king_blink"] = {"gfx_king",1,"blink",{{0, 100},{25, 100}}};
    // Animation: jump
    lvl.tileanimation["gfx_king_jump"] = {"gfx_king",7,"jump",{{9, 100},{7, 100}}};
    // Animation: on_air
    lvl.tileanimation["gfx_king_on_air"] = {"gfx_king",8,"on_air",{{8, 100}}};
    // Animation: walk
    lvl.tileanimation["gfx_king_walk"] = {"gfx_king",10,"walk",{{10, 100},{11, 100},{12, 100},{13, 100},{14, 100},{15, 100},{16, 100},{17, 100}}};
    // Animation: bubble
    lvl.tileanimation["gfx_king_bubble"] = {"gfx_king",18,"bubble",{{18, 100},{19, 100},{20, 100},{19, 100},{18, 100}}};
    // Animation: life_lost
    lvl.tileanimation["gfx_king_life_lost"] = {"gfx_king",21,"life_lost",{{21, 600},{22, 600},{23, 600}}};
    // Animation: sleeping
    lvl.tileanimation["gfx_pig_sleeping"] = {"gfx_pig",0,"sleeping",{{0, 100},{1, 100},{2, 100},{3, 100},{4, 100},{5, 100}}};
    // Animation: loitering
    lvl.tileanimation["gfx_pig_loitering"] = {"gfx_pig",6,"loitering",{{6, 100},{7, 100},{8, 100},{9, 100},{10, 100},{11, 100}}};
    // Animation: bubbling
    lvl.tileanimation["gfx_pig_bubbling"] = {"gfx_pig",13,"bubbling",{{12, 100},{13, 100}}};
    // Animation: hitting
    lvl.tileanimation["gfx_pig_hitting"] = {"gfx_pig",14,"hitting",{{14, 100},{15, 100}}};
    // Animation: poof
    lvl.tileanimation["gfx_pig_poof"] = {"gfx_pig",24,"poof",{{24, 100},{25, 100},{26, 100},{27, 100},{28, 100},{29, 100},{30, 100},{31, 100},{32, 100},{33, 100}}};

// Layers ------------------------------------------------

    // layer tilelayer: main_bg
    dang::tmx_tile tmain_bg[] = {
 {4,0,0}, {25,0,0}, {25,0,0}, {25,0,0}, {25,0,0}, {25,0,0}, {25,0,0}, {25,0,0}, {25,0,0}, {5,0,0},
 {26,0,0}, {48,0,0}, {49,0,0}, {49,0,0}, {49,0,0}, {49,0,0}, {49,0,0}, {49,0,0}, {50,0,0}, {24,0,0},
 {49,0,0}, {65,0,0}, {61,0,0}, {61,0,0}, {61,0,0}, {61,0,0}, {61,0,0}, {61,0,0}, {64,0,0}, {49,0,0},
 {61,0,0}, {61,0,0}, {61,0,0}, {61,0,0}, {61,0,0}, {61,0,0}, {61,0,0}, {61,0,0}, {61,0,0}, {61,0,0},
 {61,0,0}, {61,0,0}, {61,0,0}, {61,0,0}, {61,0,0}, {61,0,0}, {61,0,0}, {61,0,0}, {61,0,0}, {61,0,0},
 {61,0,0}, {61,0,0}, {61,0,0}, {61,0,0}, {61,0,0}, {61,0,0}, {61,0,0}, {61,0,0}, {61,0,0}, {61,0,0},
 {73,0,0}, {73,0,0}, {73,0,0}, {73,0,0}, {73,0,0}, {73,0,0}, {73,0,0}, {73,0,0}, {73,0,0}, {73,0,0},
 {1,0,0}, {1,0,0}, {1,0,0}, {1,0,0}, {1,0,0}, {1,0,0}, {1,0,0}, {1,0,0}, {1,0,0}, {1,0,0}
 };
    dang::tmx_tilelayer tlmain_bg = {"main_bg",80,tmain_bg,10,8,0};
    lvl.layers.push_back(std::make_shared<dang::tmx_tilelayer>(tlmain_bg));

    // Objects for layer: main_decoration
    dang::tmx_spriteobject somain_decoration[] = {
        {15,"15","",16,96,32,32,true,3,0},
        {16,"16","",16,128,32,32,true,3,10},
        {17,"17","",16,160,32,32,true,3,20},
        {18,"18","",272,96,32,32,true,3,0},
        {19,"19","",272,128,32,32,true,3,10},
        {20,"20","",272,160,32,32,true,3,30},
        {35,"35","",51,49,218,36,true,2,0},
        {34,"rightcandle","candle",192,128,32,32,true,3,5},
        {33,"leftcandle","candle",96,128,32,32,true,3,5}
    };
    dang::tmx_objectlayer lmain_decoration = {"main_decoration",9,somain_decoration,1};
    lvl.layers.push_back(std::make_shared<dang::tmx_objectlayer>(lmain_decoration));

    // Objects for layer: main_obj
    dang::tmx_spriteobject somain_obj[] = {
        {31,"hero","",64,192,32,32,true,4,10},
        {36,"about","button",131,91,58,32,true,6,0},
        {37,"play","button",131,123,58,32,true,6,1},
        {38,"prefs","button",131,155,58,32,true,6,2},
        {39,"piggie","",216,192,32,32,true,5,0}
    };
    dang::tmx_objectlayer lmain_obj = {"main_obj",5,somain_obj,2};
    lvl.layers.push_back(std::make_shared<dang::tmx_objectlayer>(lmain_obj));

// Images ------------------------------------------------

    lvl.images["gfx_levels_castle_tiles"] = &gfx_levels_castle_tiles;
    lvl.images["hud_ui"] = &hud_ui;
    lvl.images["main_pnk_logo"] = &main_pnk_logo;
    lvl.images["gfx_castle_decorations"] = &gfx_castle_decorations;
    lvl.images["gfx_king"] = &gfx_king;
    lvl.images["gfx_pig"] = &gfx_pig;
    lvl.images["common_menus"] = &common_menus;

    return lvl;
}
