// This file is auto generated by the SwordLord DANG Tiled Exporter.
// It will get overwritten once you re-export your tile map!
// (c) 2019-2021 by SwordLord - the coding crew


dang::tmx_level init_main_1() {

    dang::tmx_level lvl = {};

// World ------------------------------------------------

    lvl.w.width = 10;
    lvl.w.height = 8;
    lvl.w.tileWidth = 32;
    lvl.w.tileHeight = 32;

// Tilesets ------------------------------------------------

    // Tileset: gfx_levels_castle_tiles has ID: 0
    lvl.tilesets[0] = {"gfx_levels_castle_tiles",96,32,32,384,256,12,8};
    // Tileset: hud_ui has ID: 1
    lvl.tilesets[1] = {"hud_ui",105,16,16,240,112,15,7};
    // Tileset: main_pnk_logo has ID: 2
    lvl.tilesets[2] = {"main_pnk_logo",1,218,36,218,36,1,1};
    // Tileset: gfx_castle_decorations has ID: 3
    lvl.tilesets[3] = {"gfx_castle_decorations",40,32,32,320,128,10,4};
    // Tileset: gfx_king has ID: 4
    lvl.tilesets[4] = {"gfx_king",26,32,32,832,32,26,1};
    // Tileset: gfx_pig has ID: 5
    lvl.tilesets[5] = {"gfx_pig",16,32,32,512,32,16,1};
    // Tileset: common_menus has ID: 6
    lvl.tilesets[6] = {"common_menus",3,58,32,58,96,1,3};

// Animations ------------------------------------------------


// Layers ------------------------------------------------

    // layer tilelayer: main_bg
    dang::tmx_tile tmain_bg[] = {
            {4,0,0}, {25,0,0}, {25,0,0}, {25,0,0}, {25,0,0}, {25,0,0}, {25,0,0}, {25,0,0}, {25,0,0}, {5,0,0},
            {26,0,0}, {48,0,0}, {49,0,0}, {49,0,0}, {49,0,0}, {49,0,0}, {49,0,0}, {49,0,0}, {50,0,0}, {24,0,0},
            {49,0,0}, {65,0,0}, {61,0,0}, {61,0,0}, {61,0,0}, {61,0,0}, {61,0,0}, {61,0,0}, {64,0,0}, {49,0,0},
            {61,0,0}, {61,0,0}, {61,0,0}, {61,0,0}, {61,0,0}, {61,0,0}, {61,0,0}, {61,0,0}, {61,0,0}, {61,0,0},
            {61,0,0}, {61,0,0}, {61,0,0}, {61,0,0}, {61,0,0}, {61,0,0}, {61,0,0}, {61,0,0}, {61,0,0}, {61,0,0},
            {61,0,0}, {61,0,0}, {61,0,0}, {61,0,0}, {61,0,0}, {61,0,0}, {61,0,0}, {61,0,0}, {61,0,0}, {61,0,0},
            {73,0,0}, {73,0,0}, {73,0,0}, {73,0,0}, {73,0,0}, {73,0,0}, {73,0,0}, {73,0,0}, {73,0,0}, {73,0,0},
            {1,0,0}, {1,0,0}, {1,0,0}, {1,0,0}, {1,0,0}, {1,0,0}, {1,0,0}, {1,0,0}, {1,0,0}, {1,0,0}
    };
    dang::tmx_tilelayer tlmain_bg = {"main_bg",80,tmain_bg,10,8};
    lvl.layers.push_back(std::make_shared<dang::tmx_tilelayer>(tlmain_bg));

    // Objects for layer: main_decoration
    dang::tmx_spriteobject somain_decoration[] = {
            {15,"15","",16,96,32,32,true,3,0},
            {16,"16","",16,128,32,32,true,3,10},
            {17,"17","",16,160,32,32,true,3,20},
            {18,"18","",272,96,32,32,true,3,0},
            {19,"19","",272,128,32,32,true,3,10},
            {20,"20","",272,160,32,32,true,3,30},
            {35,"35","",51,49,218,36,true,2,0},
            {34,"rightcandle","candle",192,128,32,32,true,3,5},
            {33,"leftcandle","candle",96,128,32,32,true,3,5}
    };
    dang::tmx_objectlayer lmain_decoration = {"main_decoration",9,somain_decoration};
    lvl.layers.push_back(std::make_shared<dang::tmx_objectlayer>(lmain_decoration));

    // Objects for layer: main_obj
    dang::tmx_spriteobject somain_obj[] = {
            {31,"hero","",64,192,32,32,true,4,10},
            {36,"about","button",131,91,58,32,true,6,0},
            {37,"play","button",131,123,58,32,true,6,1},
            {38,"prefs","button",131,155,58,32,true,6,2},
            {39,"piggie","",216,192,32,32,true,5,0}
    };
    dang::tmx_objectlayer lmain_obj = {"main_obj",5,somain_obj};
    lvl.layers.push_back(std::make_shared<dang::tmx_objectlayer>(lmain_obj));

// Images ------------------------------------------------

    lvl.images["gfx_levels_castle_tiles"] = gfx_levels_castle_tiles;
    lvl.images["hud_ui"] = hud_ui;
    lvl.images["main_pnk_logo"] = main_pnk_logo;
    lvl.images["gfx_castle_decorations"] = gfx_castle_decorations;
    lvl.images["gfx_king"] = gfx_king;
    lvl.images["gfx_pig"] = gfx_pig;
    lvl.images["common_menus"] = common_menus;

    return lvl;
}
